#!/bin/bash

# Name - Akshay Gogate
# mail - akshay.gogate@gmail.com
# Date - 17/09/2023

# File with usernames
USER_FILE="user_list.txt"

# Check if the user file exists
if [ ! -f "$USER_FILE" ]; then
    echo "User file '$USER_FILE' not found."
    exit 1
fi

# Read user details from the file
USERS=($(cat "$USER_FILE"))

for USER in "${USERS[@]}"; do
    # check the last password change date in seconds since epoch
    LAST_CHANGE_DATE=$(chage -l "$USER" | grep "Last password change" | awk '{print $6}')
    
    # Calculate when was last password change done
    CURRENT_DATE=$(date +%s)
    DAYS_SINCE_CHANGE=$(( (CURRENT_DATE - LAST_CHANGE_DATE) / 86400 ))
    
    # Check if it is 30 or more days since change
    if [ "$DAYS_SINCE_CHANGE" -ge 30 ]; then
        # Generate a new random password
        NEW_PASSWORD=$(openssl rand -base64 12)

        # Change the user's password
        echo "$USER:$NEW_PASSWORD" | chpasswd

        # Email the new password to the user
        mail -s "Password Change Notification" "$USER" <<< "Your password has been changed. Your new password is: $NEW_PASSWORD"
        
    fi
done

echo "Password change and update completed."
